server {
    listen 80;
    root /var/www/links/public;
    index index.php;

    location / {
        try_files $uri @vite;
    }

    location ~ ^/(api|auth|docs|groups|links|user|permissions|l|admin) {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location @vite {
        proxy_pass http://linkcrop-front-app:4173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
